### ISSUE TITLE
Package outdated

### ISSUE THREAD

**Issue by igorborgest** [conda-forge/sqlalchemy-redshift-feedstock#10]
I would like to request the update of the package on the conda-forge, the last version available there is `0.7.3`.

Also posted on: https://github.com/sqlalchemy-redshift/sqlalchemy-redshift/issues/196

**Comment by synapticarbors** [comment]
@igorborgest -- I've updated the feedstock and added myself as a co-maintainer since it appeared to have been abandoned

**Comment by igorborgest** [comment]
Thanks @synapticarbors, let me help on it too! :)

https://github.com/conda-forge/sqlalchemy-redshift-feedstock/issues/11
